# Generated by Django 4.2.5 on 2023-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmusic', '0003_alter_song_audio_file_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(blank=True, choices=[('Nhạc Trẻ', 'Nhạc Trẻ'), ('Nhạc Dacce Việt', 'Nhạc Dacce Việt'), ('Rap Việt', 'Rap Việt'), ('ADM Việt', 'ADM Việt')], default=None, max_length=100, null=True),
        ),
    ]
